### ISSUE TITLE
Mix task to update sheet by name

### ISSUE THREAD

**Issue by venkatd** [GrandCru/GoogleSheets#10]
I made my own helper mix task so I don't have to duplicate information about the google sheet id.

```elixir
defmodule Mix.Tasks.Turtle.Config.Update do

  def run(_args) do
    dir = google_sheets_config(:dir)
    url = google_sheets_config(:url)
    Mix.Task.run "gs.fetch", ["-u", url, "-d", dir]
  end

  def google_sheets_config(key) do
    Application.get_env(:google_sheets, :spreadsheets)
    |> get_in([:config, key])
  end

end
```

What's your opinion of making the mix task use the values of the config file instead of requiring someone to paste them into the command line?

Cheers!

P.S. Really well written library. It has allowed me to transition from hardcoding config values without having to build an admin interface!

**Comment by jannekai** [comment]
I've done something similar and I don't see anything wrong with re-using the configuration syntax. In any case as the library user you have complete control over the configuration anyways.
