### ISSUE TITLE
mix gs.fetch fails with a MatchError

### ISSUE THREAD

**Issue by everte** [GrandCru/GoogleSheets#7]
I'm trying to use the GoogleSheets library. I followed the documentation and published my spreadsheets to the web and try to feed the initial information with the mix gs.fetch task.

mix gs.fetch -u https://spreadsheets.google.com/feeds/worksheets/1k-N20RmT62RyocEu4-MIJm11DZqlZrzV89fGIddDzIs/public/basic -d priv/data

Loading spreadsheet from url "https://spreadsheets.google.com/feeds/worksheets/1k-N20RmT62RyocEu4-MIJm11DZqlZrzV89fGIddDzIs/public/basic" and saving to /home/evert/dev/sp/priv/data

*\* (MatchError) no match of right hand side value: {:error, %HTTPoison.Error{id: nil, reason: :closed}}
    lib/google_sheets/loader/docs.ex:48: GoogleSheets.Loader.Docs.load_spreadsheet/3
    lib/google_sheets/loader/docs.ex:39: GoogleSheets.Loader.Docs.load/3
    lib/mix/tasks/gs.fetch.ex:47: Mix.Tasks.Gs.Fetch.fetch_spreadsheets/1
    (mix) lib/mix/task.ex:296: Mix.Task.run_task/3
    (mix) lib/mix/cli.ex:58: Mix.CLI.run_task/2

I tried both with "your" url in the example, as my own. Both give me a valid xml feed when getting them with curl. Sadly as an elixir newbie I can't find out how to fix the issue and add a solution.

**Comment by jannekai** [comment]
Thanks for the bug report, just wanted to say that I'm looking at this and initial reason seems to be related to this httpoison issue: https://github.com/edgurgel/httpoison/issues/130

**Comment by jannekai** [comment]
So a quick band aid if you are running Erlang 19 is to add in your own project config file the following clause:

`config :ssl, protocol_version: :"tlsv1.2"`

**Comment by everte** [comment]
Thanks! The quick band-aid workaround seems to solve the issue. I can now fetch your (example) sheets feed.

Sadly for my own sheet I'm running into errors. When getting the feed with curl, I get a valid xml document describing the google spreadsheet. Using the same url in the gs.fetch, I'm getting a 302 moved temporarily response for some reason. Given that curl gives me a proper xml feed I'm not sure what's going wrong.

`** (MatchError) no match of right hand side value: {:ok, %HTTPoison.Response{body: "<HTML>\n<HEAD>\n<TITLE>Moved Temporarily</TITLE>\n</HEAD>\n<BODY BGCOLOR=\"#FFFFFF\" TEXT=\"#000000\">\n<H1>Moved Temporarily</H1>\nThe document has moved <A HREF=\"https// .... \">here</A>.\n</BODY>\n</HTML>\n", headers: [{"Content-Type", "text/html; charset=UTF-8"}, {"Location", "https://www.google.com/...."}, {"P3P", "CP=\"This is not a P3P policy! See https://support.google.com/accounts/answer/151657?hl=en for more info.\""}, {"P3P", "CP=\"This is not a P3P policy! See https://support.google.com/accounts/answer/151657?hl=en for more info.\""}, {"Date", "Tue, 09 Aug 2016 13:59:49 GMT"}, {"Expires", "Tue, 09 Aug 2016 13:59:49 GMT"}, {"Cache-Control", "private, max-age=0"}, {"X-Content-Type-Options", "nosniff"}, {"X-Frame-Options", "SAMEORIGIN"}, {"X-XSS-Protection", "1; mode=block"}, {"Server", "GSE"}, {"Set-Cookie", "NID=84=ps67;Domain=.google.com;Path=/;Expires=Wed, 08-Feb-2017 13:59:49 GMT;HttpOnly"}, {"Set-Cookie", "NID=84=tl9n5my;Domain=.google.com;Path=/;Expires=Wed, 08-Feb-2017 13:59:49 GMT;HttpOnly"}, {"Set-Cookie", "S=apps-spreadsheets=LuNLa_Lj0iKXSg; Domain=.docs.google.com; Expires=Tue, 09-Aug-2016 14:59:49 GMT; Path=/spreadsheets/d/1Ng...; Secure; HttpOnly"}, {"Alternate-Protocol", "443:quic"}, {"Alt-Svc", "quic=\":443\"; ma=2592000; v=\"36,35,34,33,32,31,30\""}, {"Accept-Ranges", "none"}, {"Vary", "Accept-Encoding"}, {"Transfer-Encoding", "chunked"}], status_code: 302}}`

**Comment by jannekai** [comment]
Sorry didn't notice the latest comment before. If curl works OK, but using HTTPoison fails for the same URL, it's something I've not seen in any of the projects I've used this library. Only problems I've had has been in making sure the worksheet has been made publicly visible from both places.

**Comment by jaminthorns** [comment]
https://github.com/GrandCru/GoogleSheets/blob/942b6ae4438d8483b0c9aea5b5180dd15b178d94/lib/google_sheets/loader/docs.ex

It looks like the 2 HTTPoison.get calls in this file don't use the [follow_redirect: true] option. It might be undocumented behavior for Google Sheets to be giving redirects, but that seems to be the case for everte.

**Comment by jannekai** [comment]
Closing issue since the TLS/SSL protocol version selection was fixed in OTP-13753 at release http://erlang.org/download/OTP-19.0.3.README
