### ISSUE TITLE
Problem with comma when get a CSV from API

### ISSUE THREAD

**Issue by mbenatti** [GrandCru/GoogleSheets#8]
Problem: When a field have a comma inside like "description, is, this!" The google Sheets Api load the field as "\"description,is,this!\"", as the Standard implementation of CSV Escape is \", this is a problem when loading and parse using the sheets api Elixir, because the parser truncate with comma inside the field

How to test: load a google spreadsheet, the fields need to have comma inside, use the google_sheets Elixir Lib to do this and csv library(nimble_csv was used).

This can be fixed changing the escape character when download the CSV from google API, but I can't figure out to change from comma to other escape in API.

Link to download from api is like this: https://docs.google.com/spreadsheets/d/<your-id-from-public-spreadsheet>/export?gid=0&amp;format=csv

**Comment by jannekai** [comment]
This library doesn't manipulate the exported CSV returned by Google spreadsheets in any way and simply requests CSV data using URLs exposed through spreadsheet feed. From looking at my own sheets, it looks like CSV data is escaped as follows:

```
1,"Text with comma , is wrapped in ""quotes""
2,Text without commas is not wrapped
3,Text without commas can use "quotes" directly
```

I'm not sure if NimbleCSV can handle this kind of data or does it expect all fields to be always escaped. Instead I've https://github.com/CargoSense/ex_csv successfully for parsing the returned CSV format.

**Comment by mbenatti** [comment]
Thank you, I'm contacting the creator of NimbleCSV to deal with it
